
package clientews.sevicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonaServiceWs", targetNamespace = "http://servicio/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonaServiceWs {


    /**
     * 
     * @return
     *     returns java.util.List<clientews.sevicio.Persona>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPersonas", targetNamespace = "http://servicio/", className = "clientews.sevicio.ListarPersonas")
    @ResponseWrapper(localName = "listarPersonasResponse", targetNamespace = "http://servicio/", className = "clientews.sevicio.ListarPersonasResponse")
    @Action(input = "http://servicio/PersonaServiceWs/listarPersonasRequest", output = "http://servicio/PersonaServiceWs/listarPersonasResponse")
    public List<Persona> listarPersonas();

}
