
server:
  port: 7071

spring:
  application:
    name: auto
  datasource:
    url: jdbc:mysql://localhost:3306/auto
    username: root
    password: danay hija
    platform: mysql

  jpa:
    hibernate:
      ddl-auto: update